---
# playbook to install and configure an instance to wordpress
- hosts: all
  gather_facts: False 
  become: yes

  tasks:
    - name: Install Python
      command: apt install python3
      become: yes
      vars:
        ansible_python_interpreter: /usr/bin/python3