---
# tasks file for wordpres
- name: Download WordPress
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/latest.tar.gz
    validate_certs=no

- name: Extract WordPress
  unarchive:
    src=/tmp/latest.tar.gz
    dest=/var/www/
    copy=no
  become: yes

- name: Update default Apache site
  lineinfile:
    dest=/etc/apache2/sites-enabled/000-default.conf
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot {{ website_root }}" 
  become: yes

- name: Copy sample config file
  command: mv {{ website_root}}/wp-config-sample.php {{ website_root }}/wp-config.php creates={{ website_root }}/wp-config.php
  become: yes