Vagrant.configure("2") do |config|

    config.vm.box = "debian/buster64"
  
    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end
  
    config.vm.define "wp-ansible" do |m|
    end
  
  end