---
  - hosts: all
    tasks:
      - name: 'Instalando as dependencias do SO'
        apt: 
          name: '{{ item }}'
          state: latest
        become: yes
        with_items:
          - php5
          - apache2
          - libapache2-mod-php5