---
  - hosts: all
    tasks:
      - name: 'Instalando as dependencias do SO'
        apt: 
          name: '{{ item }}'
          state: latest
        become: yes
        with_items:
          - php5
          - apache2
          - libapache2-mod-php5
          - php5-gd
          - libssh2-php
          - php5-mcrypt
          - mysql-server-5.6
          - python-mysqldb
          - php5-mysql
      
      - name: 'Criando o banco de dados no MySQL'
        mysql_db:
          name: wordpress_db
          login_user: root
          state: present