---
# tasks file for server
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install required softwares
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - apache2
    - mariadb-server-10.3
    - php7.3-mysql
    - php7.3
    - libapache2-mod-php7.3
    - python3-mysqldb